Sprint 3
archebaldo77/middle.messenger.praktikum.yandex pull request #3
Opened 2022-12-09 19:46 UTC by archebaldo77

Реализован функционал:

- Routing 
- Store (попытка сделать свой redux)
- Чаты (возможность создать чат, добавить/удалить юзера, использован websocket)
- Логин, регистрация, логаут, изменение данных, аватара пользователя

2022-12-10 18:56 UTC, maks88sgt requested changes
Привет! Отличная работа. В целом, все условия спринта закрыты. Проект хорошо структурирован и разбит на модули. Неплохо используете TS, практически все основные моменты затипизированы. Идея с самописным редаксом отличная, предлагаю только немного улучшить код перед тем как двигаться дальше.  Модули из папки actions можно переработать. Логичнее будет объединить код из экшенов и назвать их контроллерами. А собственно экшены по аналогии с редаксом - это объекты, которые обрабатываются контроллерами. В остальном все ок, указал несколько незначительных моментов, которые можно поправить в процессе.

2022-12-10 18:56 UTC, maks88sgt commented on src/actions/change-user-data.ts
> +    if (status >= 400 && status <= 500) {
Этот кусок кода повторяется у Вас несколько раз, может стоит сделать отдельную функцию которая будет проверять статус респонса и обрабатывать общие для всех случаи.

2022-12-10 18:56 UTC, maks88sgt commented on src/actions/update-user-avatar.ts
> +      console.log(response);
Лучше удалять отладочную информацию перед мерджем в продакшн.

2022-12-10 18:56 UTC, maks88sgt commented on src/components/change-password-form/change-password-form.pcss
>      border-bottom: 1px solid #eaeaea;
Такие значения (например цвета, бордер-радиусы и т.д.) лучше выносить в отдельные переменные. Так будет проще поддерживать код.

2022-12-10 18:56 UTC, maks88sgt commented on src/components/chat-list/chat-list.ts
> +    if (chatName === `` || chatName === null) {
Можно упростить до 
```suggestion
    if (!chatName) {
```

2022-12-10 18:56 UTC, maks88sgt commented on src/components/input-item/input-item.pcss
> +    /* display: none; */
Лучше не держать в проекте закомментированного кода, он не имеет смысла, только затрудняет чтение.

2022-12-10 18:56 UTC, maks88sgt commented on src/components/messages/messages.ts
> +      if (this._socket !== null) {
Обычно такие проверки сокращают до 
```suggestion
      if (!this._socket) {
```

2022-12-10 18:56 UTC, maks88sgt commented on src/components/user/user.ts
> +    if (id === null || id === ` `) {
А что будет если использовать два пробела?

2022-12-10 18:56 UTC, maks88sgt commented on src/core/component.ts
> +  public componentDidMount(props: P) {
Здесь теперь не требуется отключать линтер

2022-12-10 18:56 UTC, maks88sgt commented on src/socket/socket.ts
> +    `wss://ya-praktikum.tech/ws/chats/${userId}/${selectedChatId}/${token}`
Этот урл тоже лучше вынести в константу и добавить в переменные окружения вместе с урлом для http клиента

2022-12-11 06:03 UTC, archebaldo77 commented
> 



> Привет! Отличная работа. В целом, все условия спринта закрыты. Проект хорошо структурирован и разбит на модули. Неплохо используете TS, практически все основные моменты затипизированы. Идея с самописным редаксом отличная, предлагаю только немного улучшить код перед тем как двигаться дальше. Модули из папки actions можно переработать. Логичнее будет объединить код из экшенов и назвать их контроллерами. А собственно экшены по аналогии с редаксом - это объекты, которые обрабатываются контроллерами. В остальном все ок, указал несколько незначительных моментов, которые можно поправить в процессе.

Привет Максим! Спасибо за ревью, поправил замечания. Надеюсь идею с контроллерами верно реализовал))

2022-12-11 10:18 UTC, merged